/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package myproject;

import java.net.URL;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Poorvi Malaviya
 */
public class MainPage extends javax.swing.JFrame {

    /**
     * Creates new form MainPage
     */
    public MainPage() {
        initComponents();
        setLocationRelativeTo(null);
        check();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        userlogin = new javax.swing.JLabel();
        AdminBlock = new javax.swing.JButton();
        userlogin1 = new javax.swing.JLabel();
        NewsNCirculars = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        regfield = new javax.swing.JTextField();
        ser1 = new javax.swing.JLabel();
        userlogin2 = new javax.swing.JLabel();
        userlogin3 = new javax.swing.JLabel();
        ser2 = new javax.swing.JLabel();
        BackgroudImage = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        userlogin.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        userlogin.setForeground(new java.awt.Color(255, 255, 255));
        userlogin.setText("User Login:");
        getContentPane().add(userlogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 130, 120, 30));

        AdminBlock.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        AdminBlock.setText("Admin Block");
        AdminBlock.setFocusPainted(false);
        AdminBlock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminBlockActionPerformed(evt);
            }
        });
        getContentPane().add(AdminBlock, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 10, -1, -1));

        userlogin1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        userlogin1.setForeground(new java.awt.Color(255, 255, 255));
        userlogin1.setText("Server 2");
        getContentPane().add(userlogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, 90, 30));

        NewsNCirculars.setFont(new java.awt.Font("Segoe Print", 3, 40)); // NOI18N
        NewsNCirculars.setForeground(new java.awt.Color(204, 255, 255));
        NewsNCirculars.setText("DASHBOARD");
        getContentPane().add(NewsNCirculars, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 280, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myproject/images/icons8_Login_30px.png"))); // NOI18N
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 210, -1, -1));

        regfield.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        regfield.setText("2017CA");
        regfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regfieldActionPerformed(evt);
            }
        });
        getContentPane().add(regfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 120, 30));

        ser1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myproject/images/icons8_Ok_30px.png"))); // NOI18N
        getContentPane().add(ser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, -1, -1));

        userlogin2.setFont(new java.awt.Font("Segoe Print", 0, 20)); // NOI18N
        userlogin2.setForeground(new java.awt.Color(255, 255, 255));
        userlogin2.setText("Server Status:");
        getContentPane().add(userlogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 130, 150, 30));

        userlogin3.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        userlogin3.setForeground(new java.awt.Color(255, 255, 255));
        userlogin3.setText("Server 1");
        getContentPane().add(userlogin3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, 90, 30));

        ser2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myproject/images/icons8_Cancel_30px.png"))); // NOI18N
        getContentPane().add(ser2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, -1, -1));

        BackgroudImage.setBackground(new java.awt.Color(51, 51, 51));
        BackgroudImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/myproject/images/Mnnit-background.jpg"))); // NOI18N
        BackgroudImage.setAlignmentX(3.5f);
        BackgroudImage.setAlignmentY(4.5f);
        getContentPane().add(BackgroudImage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void check()
    {
        MSQLConnection msql1 = new MSQLConnection();
        if(msql1.check)
        {
          //  System.out.println("Server1..1");
            URL urlpath= getClass().getResource("images/icons8_Ok_30px.png"); 
            ser1.setIcon(new ImageIcon(urlpath));
        }
        else
        {
            URL urlpath= getClass().getResource("images/icons8_Cancel_30px.png"); 
            ser1.setIcon(new ImageIcon(urlpath));
        }
        MSQLConn2 msql2 = new MSQLConn2();
        if(msql2.check2)
        {
          //  System.out.println("Server1..2");
             URL urlpath= getClass().getResource("images/icons8_Ok_30px.png"); 
             ser2.setIcon(new ImageIcon(urlpath));
        }
        else
        {
            URL urlpath= getClass().getResource("images/icons8_Cancel_30px.png"); 
            ser2.setIcon(new ImageIcon(urlpath));
        }
    }
    private void AdminBlockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminBlockActionPerformed

    
        this.setVisible(false);
        new AdminLogin().setVisible(true);
        // Main Form to show after the Login Form..
    
        
    }//GEN-LAST:event_AdminBlockActionPerformed

    private void regfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_regfieldActionPerformed
    static String resName;
    static String reg;
    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        try {
            // TODO add your handling code here:
            reg = regfield.getText();
            
            String sql = "select Name from studentinfo where RegNo='"+reg+"'";
            MSQLConn2 msql2 = new MSQLConn2();
            
            PreparedStatement pstmt = msql2.conn.prepareStatement(sql);
            ResultSet rs = pstmt.executeQuery();
        //    System.out.println(rs);
            while(rs.next())
                resName = rs.getString("Name");
            
        //    System.out.println(resName);
            if(resName==null)
            {
               // System.out.println("Not found");
                JOptionPane.showMessageDialog(null, "You are not a valid user please contact administrator");
            }
            else
            {
                 Dashboard dsh = new Dashboard();
                 dispose();
                 dsh.setVisible(true);
            }
                
            resName=null;
        } catch (SQLException ex) {
            Logger.getLogger(MainPage.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdminBlock;
    private javax.swing.JLabel BackgroudImage;
    private javax.swing.JLabel NewsNCirculars;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField regfield;
    private javax.swing.JLabel ser1;
    private javax.swing.JLabel ser2;
    private javax.swing.JLabel userlogin;
    private javax.swing.JLabel userlogin1;
    private javax.swing.JLabel userlogin2;
    private javax.swing.JLabel userlogin3;
    // End of variables declaration//GEN-END:variables
}
