/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package myproject;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Lokesh Chandra
 */
public class ShowData extends javax.swing.JFrame {

    /** Creates new form ShowData */
    public ShowData() {
        initComponents();
        setLocationRelativeTo(null);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        if(LostnFound.lost)
        {
            jTextField1.setText("Lost Item List");
            try {
            
               if(MainPage.dbcheck==false)
               {
                String sql ="select * from MiniProject.lost";
                MSQLConnection msql = new MSQLConnection();
                PreparedStatement pstmt = msql.conn.prepareStatement(sql);
                ResultSet rs = pstmt.executeQuery();
                
                while(rs.next())
                {
                   String a = rs.getString("RegNo");
                   String b = rs.getString("Name");
                   String c = rs.getString("Date");
                   String d = rs.getString("Time");
                   String e = rs.getString("Place");
                   String f = rs.getString("Description");
                   String g = rs.getString("Contact");
                   model.addRow(new Object[]{a,b,c,d,e,f,g});
                }
               }
               else
               {
                String sql ="select * from myproject.lost";
                MSQLConn3 msql = new MSQLConn3();
                PreparedStatement pstmt = msql.conn.prepareStatement(sql);
                ResultSet rs = pstmt.executeQuery();
                
                while(rs.next())
                {
                   String a = rs.getString("RegNo");
                   String b = rs.getString("Name");
                   String c = rs.getString("Date");
                   String d = rs.getString("Time");
                   String e = rs.getString("Place");
                   String f = rs.getString("Description");
                   String g = rs.getString("Contact");
                   model.addRow(new Object[]{a,b,c,d,e,f,g});
                }
               }
            } catch (SQLException ex) {
                Logger.getLogger(ShowData.class.getName()).log(Level.SEVERE, null, ex);
            }
            
        }
        else if(LostnFound.found)
        {
            jTextField1.setText("Found Item List");
           
            try {
                
                if(MainPage.dbcheck==false)
                {
                String sql ="select * from MiniProject.found";
                MSQLConnection msql = new MSQLConnection();
            
                PreparedStatement pstmt = msql.conn.prepareStatement(sql);
                ResultSet rs = pstmt.executeQuery();
                
                while(rs.next())
                {
                   String a = rs.getString("RegNo");
                   String b = rs.getString("Name");
                   String c = rs.getString("Date");
                   String d = rs.getString("Time");
                   String e = rs.getString("Place");
                   String f = rs.getString("Description");
                   String g = rs.getString("Contact");
                   model.addRow(new Object[]{a,b,c,d,e,f,g});
                }
                }
                else
                {
                String sql ="select * from myproject.found";
                MSQLConn3 msql = new MSQLConn3();
            
                PreparedStatement pstmt = msql.conn.prepareStatement(sql);
                ResultSet rs = pstmt.executeQuery();
                
                while(rs.next())
                {
                   String a = rs.getString("RegNo");
                   String b = rs.getString("Name");
                   String c = rs.getString("Date");
                   String d = rs.getString("Time");
                   String e = rs.getString("Place");
                   String f = rs.getString("Description");
                   String g = rs.getString("Contact");
                   model.addRow(new Object[]{a,b,c,d,e,f,g});
                }
                }
            } catch (SQLException ex) {
                Logger.getLogger(ShowData.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(null);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setAutoCreateRowSorter(true);
        jTable1.setFont(new java.awt.Font("Segoe Print", 0, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Reg No", "Item Name", "Date", "Time", "Place", "Description", "Contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setRowHeight(25);
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 620, 320));

        jButton1.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 380, -1, -1));

        jTextField1.setEditable(false);
        jTextField1.setBackground(new java.awt.Color(255, 255, 255));
        jTextField1.setFont(new java.awt.Font("Segoe Print", 1, 18)); // NOI18N
        jTextField1.setBorder(null);
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 10, 220, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 424, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
        new LostnFound().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ShowData.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ShowData().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    public javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

}
